# Code generated by kickr; DO NOT EDIT.

import "scripts/just/build.just"
import "scripts/just/clean.just"
import? "scripts/just/custom.just"

# exampleSite module commands.
mod examplesite "exampleSite/Justfile"

# list available recipes.
default:
    @just --list
