name = "hugo-primer"
license = "MIT"
licenselink = "https://github.com/kilianpaquier/hugo-primer/blob/main/LICENSE"
description = "Primer Design System to Hugo"

homepage = "https://github.com/kilianpaquier/hugo-primer"
demosite = "https://hugo-primer.kilianpaquier.dev"

tags = [
  "blog",
  "portfolio",
]
features = [
  "@primer/css",
  "@primer/primitives",
  "@primer/react",
  "@primer/view-components",
  "Primer Design System",
]

[author]
  name = "kilianpaquier"
  homepage = "https://kilianpaquier.dev"
